language: cpp
compiler:
- gcc
install:
# Upgrade GCC
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.9
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
- sudo apt-get install cppcheck
- sudo apt-get install ggcov
- sudo ln -sf /usr/bin/gcov-4.9 /usr/bin/gcov
# # Install conan
- sudo pip install conan
- sudo pip install gcovr
- pip install --user cpp-coveralls
script:
- make run_tests
after_success:
- coveralls --exclude lib --exclude tests --exclude graph --gcov-options '\-lp'
